### ISSUE TITLE
Unable to get latest Clover revision, check your internet connection or try later

### ISSUE THREAD

**Issue by KGP** [Micky1979/Build_Clover#10]
Unable to get latest Clover revision, check your internet connection or try later

![screen shot 2018-02-20 at 20 22 34](https://user-images.githubusercontent.com/8530784/36444499-e2b8214a-167b-11e8-8bbb-e258bcc6c724.png)

**Comment by fabiomartino** [comment]
Looks like a connection problem with Clover SVN's repo.
not related with the script.

**Comment by BooBerry** [comment]
The ping to svn.code.sf.net is timing out right now which is causing this issue. You can temp workaround this issue by changing to curl http_code instead.

Under **# Remote and local revisions** change...

`if ping -c 1 svn.code.sf.net >> /dev/null 2>&1; then`

To...

`if curl -sL -w "%{http_code}" svn.code.sf.net >> /dev/null; then`

And the script will function again. Saw the workaround for this posted here: http://www.insanelymac.com/forum/topic/313240-build-clovercommand-another-script-to-build-standard-clover-or-customized/page-65

**Comment by KGP** [comment]
Perfect BooBerry!!!! Awesome fix!!! Many, many thanks, man! 

Ticket can be closed

**Comment by Micky1979** [comment]
Hi all, sourceforge migrated its server to a new one last days which does not respond to the ping query (they can enable it if they want.. but usually this seems a way to protect the site from DDOS attaks). curl cannot be used because is an optional cmd in Linux so we need a function or just test if the revision exist and is a numerical string. I don't think I have the time to do that until tomorrow unless my collaborators will do that.

**Comment by Micky1979** [comment]
Solved w/o using curl, update your script to the latest version.
